#!/usr/bin/env ruby

require_relative 'git_utils.rb'

exit_if_on_the_master_branch

current_time = Time.now
new_branch_name = current_time.strftime("%Y%m%d%H%M%S%3N")
`git add -A`
`git commit -m "Committing"`

puts "Enter a meaningful branch name (leave empty if you don't need one)"
branch_name = readline.chomp.strip.gsub(" ","_").downcase

if (branch_name != "")
  checkout(branch_name)
end

`git checkout master`

exit_if_not_on_the_master_branch

checkout(new_branch_name)
`git pull jp master`
puts "new branch name:#{new_branch_name}"
auto-hot-key for automatically setting a standardized environment (ie. R# shortcuts, no VIM in studio etc)

./fetch_latest

IncomingRequest.has_imput_model_of<ViewDepartmentsRequest>()